name: Dog Monitor

on:
  schedule:
    - cron: '0 8,20 * * *'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install packages
        run: npm install

      - name: Run monitor
        run: node checkDogs.js
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1502106937175834756/4X63E3LQfHl_GecR0rMW3XONvWVjaxs8kmj0OpTXaQlDHwNRTP2rW1wNOJuAzY66RCeG

      - name: Commit updated dog list
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add previousDogs.json

          git diff --cached --quiet || git commit -m "Update dog list"

          git push